language: php

php: 7.3

before_script:
  - sudo apt-get install -y php-mongodb
  - pecl install mongodb
  - cp .env.example .env
  - phpenv config-add .travis.config.ini
  - mongo memoir_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - travis_retry composer self-update
  - travis_retry composer update --no-scripts --no-interaction

services: mongodb

script: ./vendor/bin/phpunit
