language: php

php: 7.3

before_script:
  - cp .env.example .env
  - mongo memoir_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - travis_retry composer self-update
  - travis_retry composer update --no-scripts --no-interaction

services: mongodb

script: ./bin/phpunit
